### PR TITLE
fix: scroll position should be reset when all tabs are removed

### PR DESCRIPTION
**Pull request by rinick**
resolves: https://github.com/ant-design/ant-design/issues/27712

### CODE REVIEW

**Comment by yoyo837** [comment]
Pls add some test case！

**Comment by rinick** [comment]
> Pls add some test case！

coverage is down because I removed one line of code that's no longer needed. There is no way to add tests for the line that's removed.

**Comment by yoyo837** [comment]
Need add test case to cover `tabOffsets.get(key) == null`.

**Comment by rinick** [comment]
> Need add test case to cover `tabOffsets.get(key) == null`.

test added, but like I said, I can't fix the coverage, unless I convert my change into 2 or 3 lines of code.

**Comment by zombieJ** [comment]
`+ rc-tabs@11.7.1`

**Pull request merged**
