### PR TITLE
fix: add tabs dropdown rtl classname

### PR DESCRIPTION
**Pull request by xrkffgg**
image

### CODE REVIEW

**Comment by xrkffgg** [comment]
@zombieJ

**Comment by xrkffgg** [comment]
PTAL

**Comment by zombieJ** [comment]
这两天光顾着修 bug 了，sorry~ ❤

`+ rc-tabs@11.3.1`

**Comment by xrkffgg** [comment]
Can I apply to join this organization? ❤

**Comment by zombieJ** [comment]
invited

**Pull request merged**
