### PR TITLE
Use scrollWidth/Height instead of offsetWidth/Height.

### PR DESCRIPTION
**Pull request by abramobagnara**
This fixes the computation of size for div.ant-tabs-nav

### CODE REVIEW

**Comment by afc163** [comment]
What is this fix for?

**Comment by abramobagnara** [comment]
Without this patch the sizes used does not take in account the possibility that the measured elements are constrained by a scrollbar, then leading to incorrect presentation.

**Comment by afc163** [comment]
Could you provide a reproducible demo for it?

**Comment by abramobagnara** [comment]
This is the reproducible demo:
https://codepen.io/abramo/pen/MvbVmV/?editors=1010

After a few uses of + button you will see that the bar does not show navigation buttons.

**Comment by abramobagnara** [comment]
Do you confirm the issue and the misuse of offsetWidth/offsetHeight?

**Comment by paranoidjk** [comment]
close https://github.com/react-component/tabs/issues/84

**Comment by paranoidjk** [comment]
@abramobagnara Yep, i confirmed it'a a bug. Could you rebase master to resolve confict?

**Comment by abramobagnara** [comment]
Just rebased.

**Comment by benjycui** [comment]
ping~

**Comment by abramobagnara** [comment]
Just done a new rebase.

**Comment by paranoidjk** [comment]
@zhang740 Request for review, it it's ok, bump a patch version

**Pull request merged**
