### PR TITLE
fix: be compatible with react 18 StrictMode in dev

### PR DESCRIPTION
**Pull request by TrickyPi**
closes: https://github.com/ant-design/ant-design/issues/35367

### CODE REVIEW

**Comment by afc163** [comment]
@zombieJ 看看这个

**Comment by littledian** [comment]
Hi guys, any one review and merge this?

**Comment by littledian** [comment]
It seems right to fix issue, why not merge it?

**Comment by afc163** [comment]
ping @zombieJ

**Comment by zombieJ** [comment]
`+ rc-tabs@11.14.2`

**Pull request merged**
