### PR TITLE
feat: add onNextClick and onPrevClick

### PR DESCRIPTION
**Pull request by benjycui**
Ref: https://github.com/ant-design/ant-design/issues/4395

### CODE REVIEW

**Comment by afc163** [comment]
Add some test cases?

**Comment by benjycui** [comment]
Updated.

jsdom 内各种 mock 数据。

**Comment by paranoidjk** [comment]
@benjycui https://github.com/ant-design/ant-design-mobile/issues/876 这个要不一起看下？

**Comment by paranoidjk** [comment]
7.3.0

**Pull request merged**
